# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# alpha_hull_iteration.py
# Created on: 2016-04-14 08:23:10.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: alpha_hull_iteration <OD> <input_csv> <Value> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Load required toolboxes
arcpy.ImportToolbox("Model Functions")
arcpy.ImportToolbox("C:/Temp/c177/c177.tbx")

# Script arguments
OD = arcpy.GetParameterAsText(0)
if OD == '#' or not OD:
    OD = "dest" # provide a default value if unspecified

input_csv = arcpy.GetParameterAsText(1)
if input_csv == '#' or not input_csv:
    input_csv = "D:\\DiDi_IACP\\data\\month_1.csv" # provide a default value if unspecified

Value = arcpy.GetParameterAsText(2)
if Value == '#' or not Value:
    Value = "733" # provide a default value if unspecified

# Local variables:
v_OD__min_alpha_cluster__Value__shp__5_ = ""
v_OD__min_alpha_cluster__Value__shp__4_ = v_OD__min_alpha_cluster__Value__shp__5_
month_1_Layer = "month_1_Layer"
selected__Value__shp = "D:\\DiDi_IACP\\GIS\\Min_Alpha\\selected_%Value%.shp"
minalphahull_polyline_shp = "D:\\DiDi_IACP\\GIS\\Min_Alpha\\minalphahull_polyline.shp"
v_OD__min_alpha_cluster__Value__shp = "D:\\DiDi_IACP\\GIS\\Min_Alpha\\%OD%_min_alpha_cluster_%Value%.shp"

# Process: For
arcpy.IterateCount_mb("0", "733", "1")

# Process: Add Field
arcpy.AddField_management("", "label", "LONG", "", "", "", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field
arcpy.CalculateField_management(v_OD__min_alpha_cluster__Value__shp__5_, "label", "Value", "VB", "")

# Process: Make XY Event Layer
arcpy.MakeXYEventLayer_management(input_csv, "%OD%_xx", "%OD%_yy", month_1_Layer, "PROJCS['Xian_1980_3_Degree_GK_CM_120E',GEOGCS['GCS_Xian_1980',DATUM['D_Xian_1980',SPHEROID['Xian_1980',6378140.0,298.257]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Gauss_Kruger'],PARAMETER['False_Easting',500000.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',120.0],PARAMETER['Scale_Factor',1.0],PARAMETER['Latitude_Of_Origin',0.0],UNIT['Meter',1.0]];-5123200 -10002100 10000;-100000 10000;-100000 10000;0.001;0.001;0.001;IsHighPrecision", "")

# Process: Select
arcpy.Select_analysis(month_1_Layer, selected__Value__shp, "\"label_%OD%\" = %Value%")

# Process: Minimum Alpha Hull
arcpy.MinAlphaHull_c177(selected__Value__shp, minalphahull_polyline_shp, "true", v_OD__min_alpha_cluster__Value__shp)

